spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ams-oauth2
    username: ams
    password: ams
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /reviews
  port: 8085
