spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared #tells spring where to locate the config files
  profiles:
    active: native #???
  security:
    user:
      password: amsConfigServerPassword #the password which apps will use to access its configurations
  flyway:
    enabled: false #disable flyway for config server
  autoconfigure: #disable jpa repository for config server
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, \
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, \
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration


eureka: #not register with eureka
  client:
    register-with-eureka: false #tells the built-in eureka client to not register itself with eureka, because we should act as a server
    fetch-registry: false

server:
  port: 8888 #the port where the config-server will be accessible
